# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

twilio_keys: &twilio_keys
  twilio_account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
  twilio_auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
development:
  secret_key_base: fe7f757b84e08b5d23a75f02c89abde8c1c7c5714219714bc8bb434be04b186c6bbc544ea9e6c0d78d656c3dd5177573fc63ee76f92e94ef58285d09160a4e9f
  <<: *twilio_keys
test:
  secret_key_base: 9b34e16a161e6e02bfbc67c569f104c8129e8d0b405aa7e63a4066642cfdd81ae9db6058f807db5810a9eb5564823bc54e86579eab147ed18609a6811c8b3d29
  <<: *twilio_keys

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
